### ISSUE TITLE
clarification about results about you orverlay2host

### ISSUE THREAD

**Issue by tconrado** [sergey-safarov/kazoo-configs-docker#1]
Dear dev, 

I was expecting to be able to send pkts between the host and the overlay network, but I'm not sure if the script allows that... it ran ok, changed the network on both containers, but I could not ping any ip/container from the overlay

**Comment by sergey-safarov** [comment]
Please paste here
1) commands that you used to create containers
2) command to execute my script
3) used commands to test connectivity. Line `docker exec container1 ping 192.168.1.1`

**Comment by tconrado** [comment]
dear @sergey-safarov , indeed your routine work as should, I just missed the --cap-add=NET_ADMIN requirement because tried to run it from a task, but it did not gave not a single error message despite did not show the attached ip; also, another thing that it seems to care  it the fact of having both containers running.. 

but, really thanks for your routine, it really help

**Comment by sergey-safarov** [comment]
Thank for feedback.I will add error message output.

Important. I have catch case with `iptables+nat`. That requires clean conntrack tables. 
Ticket for docker not filed.
I recommend for production servers use networks without NAT for inbound connections.

**Comment by tconrado** [comment]
> Thank for feedback.I will add error message output.
> 
> Important. I have catch case with `iptables+nat`. That requires clean conntrack tables.
> Ticket for docker not filed.
> I recommend for production servers use networks without NAT for inbound connections.

Tks for sharing! btw, I used your script to be able to forward pckts to the swarm network...
but, I'm facing another challenge: the micro applications that we offer to the clients require one ip and port. I had in the top of my mind to use docker to isolate client instances... so, the initial approach was to create a swarm network with the --internal flag, connect it using your script and forward one port from all the ipv4/24 to it, hence the network itself can have the very same IPs that are attached in the host (easy way do deploy a transparent routing), it worked fine... but when I try to create the second docker network, that shall handle a different port for all the same ipv4/24, the cli does not allow me to use the same subnet (I guess it check and notice that it is already in use another network)...

do you have any suggestion that will allow it to work? maybe directly edit the network conf file?

**Comment by sergey-safarov** [comment]
You can write own utility to interconnect linux namespaces.
Or try use [openvswitch](https://medium.com/@joatmon08/making-it-easier-docker-containers-on-open-vswitch-4ed757619af9)

**Comment by sergey-safarov** [comment]
Also some guys use [Multus CNI](https://github.com/intel/multus-cni). But i not used before.
